@startuml

class User {
    -userId: int
    -username: String
    -firstName: String
    -lastName: String
    -email: String
    -password: String
    -friends: List<int>
    -avatar: int
}

class Hero {
    -userId: int
    -name: String
    -level: int
    -experience: int
    -health: int
    -currency: int
    -items: List<int>
}

class Task {
    -taskId: int
    -name: String
    -description: String
    -difficulty: Difficulty
    -deadline: DateRange
    -reward: Reward
}

class RepeatableTask {
    -completed: int
    -frequency: Frequency
}

class OneTimeTask {
    -completed: boolean
}

class Quest {
    -questId: int
    -name: String
    -tasks: List<int>
    -completed: boolean
    -difficulty: Difficulty
    -duration: Duration
    -deadline: DateRange
    -reward: Reward
}

class Campaign {
    -campaignId: int
    -name: String
    -quests: List<int>
}

class Item {
    -itemId: int
    -name: String
    -description: String
    -rarity: Rarity
}

class Reward {
    -rewardId: int
    -name: String
    -description: String
    -currency: int
    -experience: int
    -items: List<int>
}

enum Rarity {
    COMMON
    UNCOMMON
    RARE
    EPIC
    LEGENDARY
}

enum Difficulty {
    EASY
    MEDIUM
    HARD
    INSANE
}

enum Duration {
    SHORT_TERM
    MID_TERM
    LONG_TERM
}

enum Frequency {
    DAILY
    WEEKLY
    MONTHLY
}

class DateRange {
    -startDate: LocalDate
    -endDate: LocalDate
    +in(LocalDate) boolean
}

Campaign o-- Quest
Quest o-- Task

Task --> Reward
Task --> DateRange
Task <|-- RepeatableTask
Task <|-- OneTimeTask

Quest --> DateRange
Quest --> Reward

User o-- Hero
Hero o-- Item
Reward --> Item

@enduml